version: '3.8'
name: kavatar-keycloak-dev
services:
  kavatar-keycloak-dev:
    container_name: kavatar-keycloak-dev-container
    image: quay.io/keycloak/keycloak:23.0.5
    command:
      [
        'start-dev', '--import-realm'
      ]
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=${DEFAULT_USERNAME_DEV}
      - KEYCLOAK_ADMIN_PASSWORD=${DEFAULT_PASSWORD_DEV}
      - KC_HTTP_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - kravatar-dev-network

networks:
  kravatar-dev-network:
    driver: bridge

